version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    working_directory: /usr/src
    steps:
      - checkout --no-cache
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker Image
          command: |
            npm run build:ci
